In [1]:
from ucimlrepo import fetch_ucirepo 
import pandas as pd  
from sklearn.model_selection import train_test_split

# Bank

In [2]:

# fetch dataset 
bank_marketing = fetch_ucirepo(id=222) 
  
# data (as pandas dataframes) 
X = bank_marketing.data.features 
y = bank_marketing.data.targets 

print("total length",len(X))

merged_df = pd.concat([X, y], axis=1)
merged_df.isna().sum()

total length 45211

age                0
job              288
marital            0
education       1857
default            0
balance            0
housing            0
loan               0
contact        13020
day_of_week        0
month              0
duration           0
campaign           0
pdays              0
previous           0
poutcome       36959
y                  0
dtype: int64

In [4]:
pd.unique(merged_df["previous"])

array([  0,   3,   1,   4,   2,  11,  16,   6,   5,  10,  12,   7,  18,
         9,  21,   8,  14,  15,  26,  37,  13,  25,  20,  27,  17,  23,
        38,  29,  24,  51, 275,  22,  19,  30,  58,  28,  32,  40,  55,
        35,  41])

In [5]:
merged_df = merged_df.drop(columns=['poutcome','contact','pdays'])
merged_df=merged_df.dropna()
# merged_df['y'] = merged_df['y'].map({'no': 0, 'yes': 1})

merged_df.head()

,age,job,marital,education,default,balance,housing,loan,day_of_week,month,duration,campaign,previous,y
0,58,management,married,tertiary,no,2143,yes,no,5,may,261,1,0,no
1,44,technician,single,secondary,no,29,yes,no,5,may,151,1,0,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,5,may,76,1,0,no
5,35,management,married,tertiary,no,231,yes,no,5,may,139,1,0,no
6,28,management,single,tertiary,no,447,yes,yes,5,may,217,1,0,no

In [6]:
merged_df['age_group'] = merged_df['age'].apply(lambda x: 1 if 25 < x < 65 else 0)

merged_df.head()

,age,job,marital,education,default,balance,housing,loan,day_of_week,month,duration,campaign,previous,y,age_group
0,58,management,married,tertiary,no,2143,yes,no,5,may,261,1,0,no,1
1,44,technician,single,secondary,no,29,yes,no,5,may,151,1,0,no,1
2,33,entrepreneur,married,secondary,no,2,yes,yes,5,may,76,1,0,no,1
5,35,management,married,tertiary,no,231,yes,no,5,may,139,1,0,no,1
6,28,management,single,tertiary,no,447,yes,yes,5,may,217,1,0,no,1

In [7]:
merged_df['age_group'].value_counts()

age_group
1    41239
0     1954
Name: count, dtype: int64

In [8]:
age_group_column = merged_df.pop('age_group')  # Remove the column
merged_df.insert(8, 'age_group', age_group_column)  # Insert it at position 9
merged_df.head()

,age,job,marital,education,default,balance,housing,loan,age_group,day_of_week,month,duration,campaign,previous,y
0,58,management,married,tertiary,no,2143,yes,no,1,5,may,261,1,0,no
1,44,technician,single,secondary,no,29,yes,no,1,5,may,151,1,0,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,1,5,may,76,1,0,no
5,35,management,married,tertiary,no,231,yes,no,1,5,may,139,1,0,no
6,28,management,single,tertiary,no,447,yes,yes,1,5,may,217,1,0,no

In [9]:
pd.unique(merged_df["day_of_week"])

array([ 5,  6,  7,  8,  9, 12, 13, 14, 15, 16, 19, 20, 21, 23, 26, 27, 28,
       29, 30,  2,  3,  4, 11, 17, 18, 24, 25,  1, 10, 22, 31])

In [10]:
pd.unique(merged_df["default"])

array(['no', 'yes'], dtype=object)

In [11]:
pd.unique(merged_df["month"])

array(['may', 'jun', 'jul', 'aug', 'oct', 'nov', 'dec', 'jan', 'feb',
       'mar', 'apr', 'sep'], dtype=object)

In [12]:
pd.unique(merged_df["y"])

array(['no', 'yes'], dtype=object)

In [13]:
merged_df['y'].value_counts()

y
no     38172
yes     5021
Name: count, dtype: int64

In [14]:
print(len(merged_df))

43193

In [15]:
merged_df.isna().sum()

age            0
job            0
marital        0
education      0
default        0
balance        0
housing        0
loan           0
age_group      0
day_of_week    0
month          0
duration       0
campaign       0
previous       0
y              0
dtype: int64

In [16]:
merged_df.head()

,age,job,marital,education,default,balance,housing,loan,age_group,day_of_week,month,duration,campaign,previous,y
0,58,management,married,tertiary,no,2143,yes,no,1,5,may,261,1,0,no
1,44,technician,single,secondary,no,29,yes,no,1,5,may,151,1,0,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,1,5,may,76,1,0,no
5,35,management,married,tertiary,no,231,yes,no,1,5,may,139,1,0,no
6,28,management,single,tertiary,no,447,yes,yes,1,5,may,217,1,0,no

In [17]:
columns = list(merged_df.columns)
columns.remove("age_group") 
columns.remove("marital") 
columns.insert(8, "marital") 
columns.insert(9, "age_group") 
merged_df = merged_df[columns]
merged_df.head()

,age,job,education,default,balance,housing,loan,day_of_week,marital,age_group,month,duration,campaign,previous,y
0,58,management,tertiary,no,2143,yes,no,5,married,1,may,261,1,0,no
1,44,technician,secondary,no,29,yes,no,5,single,1,may,151,1,0,no
2,33,entrepreneur,secondary,no,2,yes,yes,5,married,1,may,76,1,0,no
5,35,management,tertiary,no,231,yes,no,5,married,1,may,139,1,0,no
6,28,management,tertiary,no,447,yes,yes,5,single,1,may,217,1,0,no

In [18]:
# merged_df['job'] = merged_df['job'].str.strip()
# merged_df['marital'] = merged_df['marital'].str.strip()
# merged_df['education'] = merged_df['education'].str.strip()
# merged_df['default'] = merged_df['default'].str.strip()
# merged_df['housing'] = merged_df['housing'].str.strip()
# merged_df['loan'] = merged_df['loan'].str.strip()
# merged_df['month'] = merged_df['month'].str.strip()
# merged_df['y'] = merged_df['y'].str.strip()
# merged_df.tail()

In [19]:
len(merged_df)

43193

In [20]:
merged_df['martial_ageGroup'] = merged_df['marital'] + '_' + merged_df['age_group'].astype(str)

# Step 2: Stratified Sampling for df1 (10,000 data points)
df1_sample, remaining_data = train_test_split(
    merged_df, test_size=(1 - 6000 / len(merged_df)), stratify=merged_df['martial_ageGroup'], random_state=42
)
df1_sample = df1_sample.drop(columns=['martial_ageGroup'])
df1_sample = df1_sample.reset_index(drop=True)
df1_sample

,age,job,education,default,balance,housing,loan,day_of_week,marital,age_group,month,duration,campaign,previous,y
0,32,admin.,secondary,no,366,no,no,14,married,1,jan,366,2,0,yes
1,53,management,tertiary,no,602,yes,no,24,married,1,jul,58,2,0,no
2,50,management,secondary,no,1165,no,no,16,married,1,jul,455,1,0,yes
3,51,admin.,secondary,no,37,no,yes,20,married,1,jun,206,2,0,no
4,50,technician,secondary,no,75,yes,no,6,divorced,1,aug,101,1,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,31,management,tertiary,no,177,yes,no,15,single,1,may,124,1,0,no
5996,40,housemaid,primary,no,979,no,no,15,married,1,oct,106,4,0,no
5997,43,services,secondary,no,-1,no,no,30,married,1,jul,605,2,0,no
5998,41,technician,secondary,no,1385,no,no,17,married,1,jun,145,1,0,no
5999,48,blue-collar,secondary,no,292,no,no,30,married,1,apr,271,1,1,yes

In [21]:
len(remaining_data)

37193

In [22]:
df2_sample, remaining_data = train_test_split(
    remaining_data, test_size=(1 - 10000 / len(remaining_data)), stratify=remaining_data['martial_ageGroup'], random_state=42
)
df2_sample = df2_sample.drop(columns=['martial_ageGroup'])

df2_sample = df2_sample.reset_index(drop=True)

df2_sample

,age,job,education,default,balance,housing,loan,day_of_week,marital,age_group,month,duration,campaign,previous,y
0,33,technician,secondary,no,1064,yes,no,15,single,1,may,173,2,0,no
1,33,management,tertiary,no,417,yes,no,4,single,1,may,170,2,1,no
2,42,management,tertiary,no,157,yes,yes,28,married,1,jan,136,1,0,no
3,44,blue-collar,primary,no,-14,yes,yes,19,married,1,may,179,4,0,no
4,33,entrepreneur,tertiary,no,138,no,no,4,single,1,feb,141,2,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,53,management,tertiary,no,6388,yes,no,23,divorced,1,jul,203,2,0,no
9995,46,technician,secondary,no,1167,yes,no,21,married,1,nov,1540,2,0,yes
9996,39,services,secondary,no,117,yes,no,5,single,1,jun,190,2,0,no
9997,32,technician,secondary,no,150,no,yes,7,married,1,aug,231,2,0,no
9998,46,blue-collar,primary,no,1,yes,yes,10,married,1,jul,270,7,0,no

In [23]:
len(df2_sample),len(df1_sample)

(9999, 6000)

In [24]:
len(remaining_data)

27194

In [25]:
dfs_2000 = []

while len(remaining_data) >= 2000:
    sample_2000, remaining_data = train_test_split(
        remaining_data, test_size=(1 - 2000 / len(remaining_data)), stratify=remaining_data['martial_ageGroup'], random_state=42
    )
    dfs_2000.append(sample_2000)

# Handle remaining data points (if any) as the last DataFrame
if len(remaining_data) > 0:
    dfs_2000.append(remaining_data)

dfs_2000 = [df.drop(columns=['martial_ageGroup']) for df in dfs_2000]
dfs_2000 = [df.reset_index(drop=True) for df in dfs_2000]

In [26]:
len(dfs_2000)

14

In [27]:
dfs_2000[0].head()

,age,job,education,default,balance,housing,loan,day_of_week,marital,age_group,month,duration,campaign,previous,y
0,38,blue-collar,secondary,no,1370,yes,no,11,married,1,may,472,2,0,no
1,38,management,tertiary,no,1199,no,no,4,married,1,aug,178,1,1,yes
2,35,management,tertiary,no,361,yes,no,11,single,1,aug,169,2,0,no
3,34,blue-collar,secondary,no,2308,yes,no,7,married,1,may,1062,1,0,no
4,44,management,tertiary,no,588,yes,no,5,married,1,jun,245,2,0,no

In [28]:
for i in range(len(dfs_2000)):
    print(len(dfs_2000[i]))

2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
1194

In [29]:
for i in range(len(dfs_2000)):
    dfs_2000[i].to_csv(f'../clients_data/raw_data/client_{i}.data', header=False, index=False)

# testing data

In [30]:
df2_sample.to_csv(f'../clients_data/raw_data/client_bank.test', header=False, index=False)

In [31]:
len(df2_sample)

9999

# pre_train raw data

In [32]:
df1_sample.to_csv(f'../clients_data/raw_data/client_data_pre_trained_model.data', header=False, index=False)

In [33]:
len(df1_sample)

6000

# group raw_data

In [34]:
df2_sample.head()

,age,job,education,default,balance,housing,loan,day_of_week,marital,age_group,month,duration,campaign,previous,y
0,33,technician,secondary,no,1064,yes,no,15,single,1,may,173,2,0,no
1,33,management,tertiary,no,417,yes,no,4,single,1,may,170,2,1,no
2,42,management,tertiary,no,157,yes,yes,28,married,1,jan,136,1,0,no
3,44,blue-collar,primary,no,-14,yes,yes,19,married,1,may,179,4,0,no
4,33,entrepreneur,tertiary,no,138,no,no,4,single,1,feb,141,2,0,no

In [35]:
merge_df=df2_sample.copy()

In [36]:
single = merge_df.loc[(merge_df['marital'] == "single")]
married = merge_df.loc[(merge_df['marital'] == "married")]
age_group_1 = merge_df.loc[(merge_df['age_group'] == 1)]
age_group_0 = merge_df.loc[(merge_df['age_group'] == 0)]

print("Length: ",len(single),len(married),len(age_group_1),len(age_group_0))

Length:  2829 6006 9546 453

In [37]:
# =====Testing=============
single.to_csv(f'../clients_data/raw_data/single.data', header=False, index=False)
married.to_csv(f'../clients_data/raw_data/married.data', header=False, index=False)
age_group_1.to_csv(f'../clients_data/raw_data/age_group_1.data', header=False, index=False)
age_group_0.to_csv(f'../clients_data/raw_data/age_group_0.data', header=False, index=False)

In [38]:
# ["single","married","age_group_1","age_group_0"]

# Subgroup raw_data

In [39]:
merge_df_train=df2_sample.copy()

In [40]:
#White Men
single_agegroup1 = merge_df_train.loc[(merge_df_train['marital'] == "single") & (merge_df_train['age_group'] == 1)]
#Black Men
single_agegroup0 = merge_df_train.loc[(merge_df_train['marital'] == "single") & (merge_df_train['age_group'] == 0)]
#white Women
married_agegroup1 = merge_df_train.loc[(merge_df_train['marital'] == "married") & (merge_df_train['age_group'] == 1)]
#Black Women
married_agegroup0 = merge_df_train.loc[(merge_df_train['marital'] == "married") & (merge_df_train['age_group'] == 0)]

print("Length: ",len(single_agegroup1),len(single_agegroup0),len(married_agegroup1),len(married_agegroup0))

Length:  2583 246 5835 171

In [41]:

single_agegroup1.to_csv(f'../clients_data/raw_data/single_agegroup1.data', header=False, index=False)
single_agegroup0.to_csv(f'../clients_data/raw_data/single_agegroup0.data', header=False, index=False)
married_agegroup1.to_csv(f'../clients_data/raw_data/married_agegroup1.data', header=False, index=False)
married_agegroup0.to_csv(f'../clients_data/raw_data/married_agegroup0.data', header=False, index=False)

In [42]:
# ["single_agegroup1","single_agegroup0","married_agegroup1","married_agegroup0"]